SET NAMES UTF8;
DROP DATABASE IF EXISTS money;
CREATE DATABASE money CHARSET=UTF8;
USE money;
CREATE TABLE user(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(50),
    upwd VARCHAR(50),
    phone VARCHAR(50),
    friend VARCHAR(50)
)